const GET_PROPERTY_LIST = 'GET_PROPERTY_LIST'
const GET_PROPERTY_LIST_SUCCESS = 'GET_PROPERTY_LIST_SUCCESS'
const GET_PROPERTY_LIST_FAILURE = 'GET_PROPERTY_LIST_FAILURE'
const SET_FILTERS = 'SET_FILTERS'

export default {
  GET_PROPERTY_LIST,
  GET_PROPERTY_LIST_SUCCESS,
  GET_PROPERTY_LIST_FAILURE,
  SET_FILTERS,
}
