const GET_PROPERTY_LIST = 'GET_PROPERTY_LIST'
const GET_PROPERTY_LIST_SUCCESS = 'GET_PROPERTY_LIST_SUCCESS'
const GET_PROPERTY_LIST_FAILURE = 'GET_PROPERTY_LIST_FAILURE'
const SET_ALL_FILTERS = 'SET_ALL_FILTERS'
const SET_FILTER = 'SET_FILTER'

export default {
  GET_PROPERTY_LIST,
  GET_PROPERTY_LIST_SUCCESS,
  GET_PROPERTY_LIST_FAILURE,
  SET_ALL_FILTERS,
  SET_FILTER,
}
