const SET_PROPERTY = 'SET_PROPERTY'
const GET_PROPERTY = 'GET_PROPERTY'
const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS'
const GET_PROPERTY_FAILURE = 'GET_PROPERTY_FAILURE'

export default {
  SET_PROPERTY,
  GET_PROPERTY,
  GET_PROPERTY_SUCCESS,
  GET_PROPERTY_FAILURE,
}
